#pragma once

#include "config.h"

typedef enum {
    /* TITLE SCREEN */
    TEXTURE_TITLE_BACKGROUND,
    TEXTURE_TITLE_PROMPT,
    TEXTURE_WATERFALL_CREST_0,
    TEXTURE_WATERFALL_CREST_1,
    TEXTURE_WATERFALL_WAVE_0,
    TEXTURE_WATERFALL_WAVE_1,
    TEXTURE_WATERFALL_WAVE_2,
    TEXTURE_TRIFORCE_GLOW_MASK,
    TEXTURE_TRIFORCE_OCCLUSION,

    /* MENU SCREENS */
    TEXTURE_SELECT_BACKGROUND,
    TEXTURE_REGISTER_BACKGROUND,
    TEXTURE_ELIMINATION_BACKGROUND,
    TEXTURE_MENU_FONT,
    TEXTURE_LINK_GREEN,
    TEXTURE_LINK_BLUE,
    TEXTURE_LINK_RED,
    TEXTURE_LIFE_HEART_FULL,
    TEXTURE_LIFE_HEART_HALF,
    TEXTURE_LIFE_HEART_EMPTY,
    TEXTURE_SELECTION_TILE_RED,

    TEXTURE_COUNT
} TextureType;

extern Texture2D textures[TEXTURE_COUNT];

bool initTextureMap();
void endTextureMap();
